### ISSUE TITLE
Container state improper

### ISSUE THREAD

**Issue by aawdls** [dls-controls/dev-c7#67]
The first time I try `run-dev-c7.sh` after logging in, I get
```
main [tdq39642@pc0095 dev-c7]$ run-dev-c7.sh 
restarting stopped dev-c7 container latest ...
Error: OCI runtime error: unable to start container "12d99d6be5cb547434b3c600e27476b25604350990c685e4651d108a8ae347b4": /usr/bin/crun: error stat'ing file `/dls_sw/work`: Too many levels of symbolic links
Error: can only create exec sessions on running containers: container state improper
```
The "container state improper" error is always there. The "too many levels of symbolic links" is noot.

I can always get it to work by using `-d`, and in practice this is not a great cost, but it's a bit annoying.

**Comment by gilesknap** [comment]
@aawdls my guess is that this is due to an automount. At least that is the error I get when I try to look at someone else's home folder inside dev-c7 (and these are automounted).

If that is right then doing this before launch would likely fix the issue.
```
ls /dls_sw/work
```

I'm beginning to thing that restarting the stopped container is not that helpful. Maybe I should delete the stopped container and start a new one. We can still share one running container between all prompts.

**Comment by gilesknap** [comment]
@aawdls I've made a launcher that deletes stopped container instead of restarting it.

Please can you see if you are happy with it.
https://github.com/dls-controls/dev-c7/blob/dev/run-dev-c7.sh

**Comment by aawdls** [comment]
Looks good, thanks

**Comment by gilesknap** [comment]
Since this we have had an upgrade to podman 4.3 which should fix this issue.

I have re-instated container restarting in the new c7 script.

@aawdls I'm closing this issue for now but feel free to re-open if you find there are still issues.
